

Running tests... 
----------------------------------------------------------------------
 test_search_selenium_ide (test_baidu.Baidu) ... ERROR (0.014926)s
 test_search_setting (test_baidu.Baidu) ... ERROR (0.009662)s

======================================================================
ERROR [0.014926s]: test_baidu.Baidu.test_search_selenium_ide
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jokerzhang/Desktop/MyFramework/case/test_baidu.py", line 23, in setUp
    self.driver = webdriver.Chrome()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home


======================================================================
ERROR [0.009662s]: test_baidu.Baidu.test_search_setting
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jokerzhang/Desktop/MyFramework/case/test_baidu.py", line 23, in setUp
    self.driver = webdriver.Chrome()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home


----------------------------------------------------------------------
Ran 2 tests in 0:00:00

FAILED
 (Errors=2)

Generating HTML reports... 
reports/TestResults_test_baidu.Baidu_2019-04-22_22-41-07.html
